services:
  booking_back_service:
    image: booking-api-image:latest
    container_name: booking_back
    env_file:
      - .env
#    ports:
#      - "8000:8000"
    networks:
      - myNetwork

  booking_celery_worker_service:
    image: booking-api-image:latest
    container_name: booking_celery_worker
    env_file:
      - .env
    command: "celery --app=src.tasks.celery_app:celery_instance worker -l INFO"
    networks:
      - myNetwork

  booking_celery_beat_service:
    image: booking-api-image:latest
    container_name: booking_celery_beat
    env_file:
      - .env
    command: "celery --app=src.tasks.celery_app:celery_instance beat -l INFO"
    networks:
      - myNetwork

networks:
  myNetwork:
    external: true
