"""Add Images

Revision ID: db539cf86009
Revises: 3218e142dd53
Create Date: 2024-10-20 10:26:37.148672

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "db539cf86009"
down_revision: Union[str, None] = "3218e142dd53"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hotel_images",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("image_path", sa.String(length=1000), nullable=False),
        sa.Column("hotel_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["hotel_id"],
            ["hotels.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("hotel_images")
    # ### end Alembic commands ###
